### ISSUE TITLE
bbqsql not running

### ISSUE THREAD

**Issue by Pen-Ace** [Neohapsis/bbqsql#57]
When i run the application it throws this error back: 

Traceback (most recent call last):
  File "/usr/local/bin/bbqsql", line 3, in <module>
    from bbqsql import *
  File "/usr/local/lib/python2.7/dist-packages/bbqsql/__init__.py", line 30, in <module>
    from lib import *
  File "/usr/local/lib/python2.7/dist-packages/bbqsql/lib/__init__.py", line 1, in <module>
    import api
  File "/usr/local/lib/python2.7/dist-packages/bbqsql/lib/api.py", line 3, in <module>
    from .technique import *
  File "/usr/local/lib/python2.7/dist-packages/bbqsql/lib/technique.py", line 8, in <module>
    from gevent.coros import Semaphore
ImportError: No module named coros

I installed the latest version, and beforehand purged what was there before.
ACE

**Comment by saltasatelites** [comment]
Same problme here on a fresh Arch Linux install

**Comment by saltasatelites** [comment]
hi, delete line 8 
from gevent.coros import Semaphore
and works fine

**Comment by muhviehstah** [comment]
replace the line with 

from gevent.lock import Semaphore

**Comment by rhertzog** [comment]
This was fixed in https://github.com/Neohapsis/bbqsql/commit/2d2541b40df2d8b9a215f8bc11005c9037642c99

You can close the ticket.

**Comment by Kali29linux** [comment]
how can i fix it\

**Comment by HugoFiermein** [comment]
haha same problem

**Comment by HugoFiermein** [comment]
https://stackoverflow.com/questions/63892745/bad-problems-with-install-bbqsql
