### ISSUE TITLE
ImportError: cannot import name filterfalse

### ISSUE THREAD

**Issue by koxu1996** [Neohapsis/bbqsql#59]
I am unable to install BBQSQL:
```
andrew@andrew-desktop:~$ sudo pip2.7 install bbqsql
Collecting bbqsql
  Downloading BBQSQL-1.2.tar.gz (41kB)
    100% |████████████████████████████████| 51kB 1.1MB/s 
Requirement already satisfied: gevent in /usr/local/lib/python2.7/dist-packages/gevent-1.2.2-py2.7-linux-x86_64.egg (from bbqsql)
Collecting requests<1.0 (from bbqsql)
  Downloading requests-0.14.2.tar.gz (361kB)
    100% |████████████████████████████████| 368kB 1.3MB/s 
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/requests.egg-info
    writing pip-egg-info/requests.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/requests.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/requests.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/requests.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vUnK60/requests/setup.py", line 69, in <module>
        'Programming Language :: Python :: 3.3',
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 279, in run
        self.find_sources()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 294, in find_sources
        mm.run()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 525, in run
        self.add_defaults()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 561, in add_defaults
        sdist.add_defaults(self)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/py36compat.py", line 34, in add_defaults
        self._add_defaults_python()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/sdist.py", line 133, in _add_defaults_python
        build_py = self.get_finalized_command('build_py')
      File "/usr/lib/python2.7/distutils/cmd.py", line 311, in get_finalized_command
        cmd_obj = self.distribution.get_command_obj(command, create)
      File "/usr/lib/python2.7/distutils/dist.py", line 845, in get_command_obj
        klass = self.get_command_class(command)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 491, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2302, in load
        return self.resolve()
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 12, in <module>
        from six.moves import map, filter, filterfalse
    ImportError: cannot import name filterfalse
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vUnK60/requests/
```

**Comment by koxu1996** [comment]
Temporary workaround:
```
$ git clone https://github.com/Neohapsis/bbqsql.git
$ cd bbqsql
$ sed -i.bak "s/</<=/g" setup.py
$ sed -i.bak "s/gevent.coros/gevent.lock/g" bbqsql/lib/technique.py
$ chmod +x setup.py
$ sudo ./setup.py install
```

**Comment by koxu1996** [comment]
Upgrading setuptools helped:
`$ pip2.7 install --upgrade setuptools`
